
services:
  ovms_server:
    build: 
      dockerfile: Dockerfile
      platforms: ["linux/amd64", "linux/arm64"]

  ovms_migrator:
    build:
      dockerfile: db/Dockerfile
      platforms: ["linux/amd64", "linux/arm64"]
